CREATE TABLE PROJECT (
    ID                 INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    PROJECT_NUMBER     VARCHAR(255),
    NAME               VARCHAR(255)  NOT NULL,
    CLIENT             VARCHAR(255)  NOT NULL,
    COORDINATOR        VARCHAR(255)  NOT NULL,
    ALIAS              VARCHAR(255)  NOT NULL,
    START_DATE         DATE,
    END_DATE           DATE,
    CONTRACT_DATE      DATE,
    ELIGIBLE_COSTS     DOUBLE PRECISION NOT NULL,
    FUNDING_RATE       DOUBLE PRECISION NOT NULL,
    GRANT_AMOUNT       DOUBLE PRECISION NOT NULL,
    INDIRECT_COST_RATE DOUBLE PRECISION NOT NULL
);